# Generated by Django 4.2.6 on 2023-10-10 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_products_category_products_image_products_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
